// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	CompanyID   int64
	LogoUrl     string
	UserID      pgtype.Int8
	CompanyName string
	CreatedAt   pgtype.Timestamptz
}

type Invoice struct {
	ID             int64
	InvoiceID      pgtype.Text
	UserID         pgtype.Int8
	CompanyID      pgtype.Int8
	Address        string
	AccountNumber  string
	TotalAmount    pgtype.Numeric
	InvoiceDate    pgtype.Date
	InvoiceDueDate pgtype.Date
	Status         pgtype.Text
	CreatedAt      pgtype.Timestamptz
	InvoiceType    pgtype.Text
}

type InvoiceItem struct {
	InvoiceItemID int64
	InvoiceID     string
	Item          string
	Amount        pgtype.Numeric
	CreatedAt     pgtype.Timestamptz
}

type User struct {
	UserID    int64
	Email     pgtype.Text
	CreatedAt pgtype.Timestamptz
	Name      pgtype.Text
}
